### ISSUE TITLE
New FFI Interface Error Branch - "TypeError: 'list' object is not callable"

### ISSUE THREAD

**Issue by adam-hartshorne** [rdyro/torch2jax#20]
I realised that I made a huge mistake and that when I thought I was testing the new version of torch2jax for FFI, I hadn't actually overwritten the old version.

Now, when I try and run the simple test example shown below, I get the following error

```
Traceback (most recent call last):
  File "/media/adam/shared_drive/PycharmProjects/smart_flow/new_torch2jax_test.py", line 32, in <module>
    out = jax_fn(a, b)
  File "/home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/api.py", line 271, in wrapped_fn
    ret = wrapped_fn_flat(*jax.tree.flatten(args)[0])
  File "/home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/api.py", line 69, in wrapped_flat_fn
    return fn_(*args_flat, fn_id=f"{id:d}")
TypeError: 'list' object is not callable
```

```
import torch
import jax
from jax import numpy as jnp
from torch2jax import torch2jax  # this converts a Python function to JAX
from torch2jax import Size, dtype_t2j  # this is torch.Size, a tuple-like shape representation


def torch_fn(a, b):
    return a + b


shape = (10, 2)
a, b = torch.randn(shape), torch.randn(shape)
jax_fn = torch2jax(torch_fn, a, b)  # without output_shapes, torch_fn **will be evaluated once**
jax_fn = torch2jax(torch_fn, a, b, output_shapes=Size(a.shape))  # torch_fn will NOT be evaluated

# you can specify the whole input and output structure without instantiating the tensors
# torch_fn will NOT be evaluated
jax_fn = torch2jax(
    torch_fn,
    jax.ShapeDtypeStruct(a.shape, dtype_t2j(a.dtype)),
    jax.ShapeDtypeStruct(b.shape, dtype_t2j(b.dtype)),
    output_shapes=jax.ShapeDtypeStruct(a.shape, dtype_t2j(a.dtype)),
)

prngkey = jax.random.PRNGKey(0)
device = jax.devices("cuda")[0]  # both CPU and CUDA are supported
a = jax.device_put(jax.random.normal(prngkey, shape), device)
b = jax.device_put(jax.random.normal(prngkey, shape), device)

# call the no-copy torch function
out = jax_fn(a, b)

# call the no-copy torch function **under JIT**
out = jax.jit(jax_fn)(a, b)
```

Edit - I have found the error is related to having JAX 0.4.33 rather than 0.4.35 installed.

**Comment by rdyro** [comment]
Can you try:
```bash
$ rm -rf ~/.cache/torch2jax
```

It might be using the old C++ plugin module

**Comment by adam-hartshorne** [comment]
I have tried that, see below with v0.4.33. This goes away when using v0.4.35

```
Cache empty, we will compile the C++ extension component now...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/adam/.cache/torch2jax/cpython-310-linux-x86_64--jax-0.4.33--torch2jax-0.5.0/build.ninja...
/home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module torch2jax_cpp...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/5] c++ -MMD -MF cpu_impl.o.d -DTORCH_EXTENSION_NAME=torch2jax_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/TH -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -isystem /home/adam/.local/lib/python3.10/site-packages/jaxlib/include -DTORCH2JAX_WITH_CUDA -c /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/cpp/cpu_impl.cpp -o cpu_impl.o 
[2/5] c++ -MMD -MF common.o.d -DTORCH_EXTENSION_NAME=torch2jax_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/TH -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -isystem /home/adam/.local/lib/python3.10/site-packages/jaxlib/include -DTORCH2JAX_WITH_CUDA -c /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/cpp/common.cpp -o common.o 
[3/5] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output main.cuda.o.d -DTORCH_EXTENSION_NAME=torch2jax_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/TH -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DTORCH2JAX_WITH_CUDA -O3 -isystem /home/adam/.local/lib/python3.10/site-packages/jaxlib/include -std=c++17 -c /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/cpp/main.cu -o main.cuda.o 
[4/5] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output gpu_impl.cuda.o.d -DTORCH_EXTENSION_NAME=torch2jax_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/TH -isystem /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/adam/anaconda3/envs/jax_torch_latest/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DTORCH2JAX_WITH_CUDA -O3 -isystem /home/adam/.local/lib/python3.10/site-packages/jaxlib/include -std=c++17 -c /home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/cpp/gpu_impl.cu -o gpu_impl.cuda.o 
[5/5] c++ cpu_impl.o common.o main.cuda.o gpu_impl.cuda.o -shared -lcuda -L/home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o torch2jax_cpp.so
Loading extension module torch2jax_cpp...
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/adam/shared_drive/PycharmProjects/smart_flow/new_torch2jax_test.py", line 32, in <module>
    out = jax_fn(a, b)
  File "/home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/api.py", line 271, in wrapped_fn
    ret = wrapped_fn_flat(*jax.tree.flatten(args)[0])
  File "/home/adam/anaconda3/envs/jax_torch_latest/lib/python3.10/site-packages/torch2jax/api.py", line 69, in wrapped_flat_fn
    return fn_(*args_flat, fn_id=f"{id:d}")
TypeError: 'list' object is not callable
```

**Comment by rdyro** [comment]
You are absolutely right! The behavior of `ffi.ffi_call` changed in JAX version 0.4.34 onwards.

I just pushed a commit that adds detection, whether it's the new or old `ffi_call` method call interface. I tested it on my end, but I really need to set up proper CI testing. Please re-open the issue if the fix doesn't work for you.

Thanks so much for identifying this!
